name: HardcoreSeason
version: '${project.version}'
main: me.exitium.hardcoreseason.HardcoreSeason
api-version: 1.18

depend: [ Vault, Multiverse-Core, Multiverse-Inventories ]

commands:
  hchelp:
    description: Gives information about the hardcore season.
    aliases: [ hc ]
    usage: /<command>
  hcenter:
    description: Enter the hardcore world.
    aliases: [ hcstart ]
    usage: /<command>
  hcexit:
    description: Leave the hardcore world.
    aliases: [ hcleave ]
    usage: /<command>
  hclist:
    description: Show all hardcore players and their status.
    aliases: [ hcwho ]
    usage: /<command>
  hcstats:
    description: Get a book containing hardcore statistics.
    usage: /<command>
  hcspectate:
    description: Teleports a spectator to an alive player.
    aliases: [ hcspec ]
    usage: /<command> <player-name>